import { readFile } from "node:fs/promises";
import { Wexel, createBusyBoxRunner } from "../packages/wexel/dist/index.js";
import BusyBoxModule from "../packages/wexel/assets/busybox/busybox.js";
const coreBytes = await readFile(new URL("../packages/wexel/assets/core.wasm", import.meta.url));
const wasmBytes = await readFile(new URL("../packages/wexel/assets/busybox/busybox.wasm", import.meta.url));
const busybox = await createBusyBoxRunner(BusyBoxModule, wasmBytes);
const runtime = await Wexel.create({ coreBytes });
const result = await busybox.run({ args: ["busybox", "echo", "BusyBox dentro do Wexel"] });
console.log("BusyBox WASM:", result);
console.log(await runtime.shell.exec("pwd"));
